local-phone-apps = Apollo \
                   ApplicationsProvider \
                   BackupRestoreConfirmation \
                   BasicDreams \
                   Bluetooth \
                   Browser \
                   Calculator \
                   Calendar \
                   CalendarProvider \
                   CellBroadcastReceiver \
                   CertInstaller \
                   ChromeBookmarksSyncAdapter \
                   CMAccount \
                   CMFileManager \
                   CMUpdater \
                   CMWallpapers \
                   ConfigUpdater \
                   Contacts \
                   ContactsProvider \
                   DefaultContainerService \
                   DeskClock \
                   Development \
                   DeviceSettings \
                   DownloadProvider \
                   DownloadProviderUi \
                   DrmProvider \
                   DSPManager \
                   Email2 \
                   Exchange2 \
                   FaceLock \
                   FusedLocation \
                   Galaxy4 \
                   Gallery2 \
                   GenieWidget \
                   Gmail \
                   GmsCore \
                   GoogleBackupTransport \
                   GoogleCalendarSyncAdapter \
                   GoogleContactsSyncAdapter \
                   GoogleEars \
                   GoogleFeedback \
                   GoogleLoginService \
                   GooglePartnerSetup \
                   GooglePlus \
                   GoogleServicesFramework \
                   GoogleTTS \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LatinIME \
                   LatinImeDictionaryPack \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   LockClock \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   MediaUploader \
                   Mms \
                   NetworkLocation \
                   NoiseField \
                   OneTimeInitializer \
                   PackageInstaller \
                   PhaseBeam \
                   Phone \
                   Phonesky \
                   PhotoTable \
                   PicoTts \
                   QuickSearchBox \
                   SamsungServiceMode \
                   Settings \
                   SettingsProvider \
                   SetupWizard \
                   SharedStorageBackup \
                   SoundRecorder \
                   Stk \
                   SystemUI \
                   TalkBack \
                   TelephonyProvider \
                   Term \
                   ThemeChooser \
                   ThemeManager \
                   Torch \
                   Trebuchet \
                   UserDictionaryProvider \
                   VideoEditor \
                   VisualizationWallpapers \
                   VoiceDialer \
                   VoiceSearchStub \
                   VpnDialogs \
                   WAPPushManager
