local-phone-apps = ApplicationsProvider \
                   BackupRestoreConfirmation \
                   BasicDreams \
                   Bluetooth \
                   CellBroadcastReceiver \
                   CertInstaller \
                   ChromeBookmarksSyncAdapter \
                   DefaultContainerService \
                   DrmProvider \
                   DSPManager \
                   FaceLock \
                   Galaxy4 \
                   GmsCore \
                   GoogleBackupTransport \
                   GoogleCalendarSyncAdapter \
                   GoogleContactsSyncAdapter \
                   GoogleEars \
                   GoogleFeedback \
                   GoogleLoginService \
                   GooglePartnerSetup \
                   GoogleServicesFramework \
                   GoogleTTS \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LatinIME \
                   LatinImeDictionaryPack \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   MediaUploader \
                   NoiseField \
                   PhaseBeam \
                   PhotoTable \
                   PicoTts \
                   SamsungServiceMode \
                   SharedStorageBackup \
                   Stk \
                   UserDictionaryProvider \
                   VisualizationWallpapers \
                   WAPPushManager
